name: Metrix
on: push
jobs:
  build:
    strategy:
      matrix:
        node-version: [12, 13, 14]
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: "${{ metrix.operating-system }}"
    steps: 
      - name: get code
        uses: actions/checkout@v3
      - name: Install nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: install dependencies
        run: npm ci
      - name: build project 
        run: npm run build
