name: Metrix
on: push
jobs:
  build:
    strategy:
     matrix:
      node: [12,13,14]
      Operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ metrix.operating-system }}
    steps: 
      - name: get code
        uses: actions/checkout@v3
      - name: Install nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ metrix.node}}
      - name: install dependencies
        run: npm ci
      - name: build project 
        run: npm run build
